version: 2
builds:
  - main: ./cmd/courier/main.go
    binary: courier
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

changelog:
  filters:
    exclude:
      - "^Update CHANGELOG.md"

archives:
  - files:
      - LICENSE
      - README.md
